# build a minimal interpreter
CFLAGS_EXTRA += -O2 -DNDEBUG -D_WASI_EMULATED_MMAN -fblocks

PROG = micropython

FROZEN_MANIFEST =

MICROPY_PY_BTREE = 0
MICROPY_PY_FFI = 0
MICROPY_PY_SOCKET = 0
MICROPY_PY_THREAD = 0
MICROPY_PY_TERMIOS = 0
MICROPY_PY_USSL = 0
